FROM nginx:alpine

WORKDIR /app

# Copy the current directory contents into the container at /app
COPY html-dir /usr/share/nginx/html/

# Make port 80 available to the world outside this container
EXPOSE 80
